In [1]:
import datetime

current_time = datetime.datetime.now()
print("Current time is:", current_time)

Current time is: 2024-02-14 19:15:16.673112


In [2]:
current_time = datetime.datetime.now().time()
print("Current time is:", current_time)

Current time is: 19:16:13.095801


In [4]:
import datetime

# Define the two times
time1 = datetime.datetime(19:15:16.673112)  # Example time 1
time2 = datetime.datetime(19:16:13.095801)  # Example time 2

# Calculate the difference
time_difference = time2 - time1

print("Time difference:", time_difference)

SyntaxError: invalid syntax (665071412.py, line 4)

In [5]:
import datetime

# Define the two times
time1 = datetime.time(12, 30)  # Example time 1
time2 = datetime.time(14, 45)  # Example time 2

# Calculate the difference
time_difference_hours = time2.hour - time1.hour
time_difference_minutes = time2.minute - time1.minute

# Adjust minutes if negative
if time_difference_minutes < 0:
    time_difference_hours -= 1
    time_difference_minutes += 60

print("Time difference:", time_difference_hours, "hours and", time_difference_minutes, "minutes")


Time difference: 2 hours and 15 minutes


In [10]:
timea = datetime.time(19, 15, 16)
timeb = datetime.time(19, 16, 13)
print(timeb - timea)

TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'

In [2]:
import csv
from faker import Faker
import random
from datetime import datetime, timedelta

# Initialize Faker to generate random data
fake = Faker()

# Define the number of rows
num_rows = 200000

# Define possible values for categorical variables
premium_frequencies = ['A', 'B', 'C']  # Example premium frequencies
product_codes = ['301', '302', '303']  # Example product codes
product_names = ['Product A', 'Product B', 'Product C']  # Example product names
insured_sexes = ['M', 'F']  # Example sexes
policy_statuses = ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'REINSTATED']  # Example policy statuses

# Define a function to generate a random date within a range
def random_date(start_date, end_date):
    return start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

# Define the start and end dates for issuance and commencement
start_issuance_date = datetime(2010, 1, 1)
end_issuance_date = datetime(2022, 12, 31)
start_commencement_date = datetime(2010, 1, 1)
end_commencement_date = datetime(2022, 12, 31)

# Open a CSV file to write the dummy data
with open('dummy_data.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    
    # Write the header row
    writer.writerow(["PROPOSAL_NO", "POLICY_NO", "PREMIUM_FREQUENCY", "PPR_PRODCD", "PRODUCT_NAME",
                     "ISSUANCE_DATE", "COMMENCEMENT_DATE", "NETPREMIUM", "BASIC_SUMASSURED",
                     "INSURED_SEX", "INSURED_DOB", "COVERMULTIPLE", "BENEFIT_TERM", "BASIC_CASH_VALUE",
                     "Group Code", "POLICY_STATUS", "Status_code"])
    
    # Generate and write dummy data for the specified number of rows
    for _ in range(num_rows):
        issuance_date = random_date(start_issuance_date, end_issuance_date)
        commencement_date = random_date(start_commencement_date, end_commencement_date)
        
        writer.writerow([
            fake.random_number(digits=9),  # Proposal number
            fake.random_number(digits=9),  # Policy number
            random.choice(premium_frequencies),  # Premium frequency
            random.choice(product_codes),  # Product code
            random.choice(product_names),  # Product name
            issuance_date.strftime('%d/%m/%Y'),  # Issuance date
            commencement_date.strftime('%d/%m/%Y'),  # Commencement date
            fake.random_number(digits=6),  # Net premium
            fake.random_number(digits=6),  # Basic sum assured
            random.choice(insured_sexes),  # Insured sex
            fake.date_of_birth(minimum_age=18, maximum_age=80).strftime('%d/%m/%Y'),  # Insured DOB
            fake.random_number(digits=5),  # Cover multiple
            fake.random_number(digits=2),  # Benefit term
            fake.random_number(digits=9),  # Basic cash value
            fake.random_letter() + '-' + str(fake.random_number(digits=2)),  # Group code
            random.choice(policy_statuses),  # Policy status
            fake.random_number(digits=1)  # Status code
        ])


In [2]:
pip install faker

  Obtaining dependency information for faker from https://files.pythonhosted.org/packages/be/de/8bd27eb39eda9e06803b8ac89ae32edff0b7d206f4b69cd2f558ae24620e/Faker-23.2.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
    --------------------------------------- 0.0/1.7 MB 495.5 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/1.7 MB 1.7 MB/s eta 0:00:01
   ----------- ---------------------------- 0.5/1.7 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 1.4/1.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 7.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
import csv
from faker import Faker
import random
from datetime import datetime, timedelta

# Initialize Faker to generate random data
fake = Faker()

# Define the number of rows
num_rows = 200000

# Define a function to calculate the cover multiple based on the provided formula
def calculate_cover_multiple(commencement_date, dob):
    days = (commencement_date - dob).days + 1
    years = days / 365.25
    return min(round(years), 100)  # Ensure the value does not exceed 100

# Define the start and end dates for issuance and commencement
start_issuance_date = datetime(2010, 1, 1)
end_issuance_date = datetime(2022, 12, 31)
start_commencement_date = datetime(2010, 1, 1)
end_commencement_date = datetime(2022, 12, 31)

# Open a CSV file to write the dummy data
with open('dummy_dataII.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    
    # Write the header row
    writer.writerow(["PROPOSAL_NO", "POLICY_NO", "PREMIUM_FREQUENCY", "PPR_PRODCD", "PRODUCT_NAME",
                     "ISSUANCE_DATE", "COMMENCEMENT_DATE", "NETPREMIUM", "BASIC_SUMASSURED",
                     "INSURED_SEX", "INSURED_DOB", "COVERMULTIPLE", "BENEFIT_TERM", "BASIC_CASH_VALUE",
                     "Group Code", "POLICY_STATUS", "Status_code"])
    
    # Generate and write dummy data for the specified number of rows
    for _ in range(num_rows):
        issuance_date = fake.date_between(start_date=start_issuance_date, end_date=end_issuance_date)
        commencement_date = fake.date_between(start_date=start_commencement_date, end_date=end_commencement_date)
        dob = fake.date_of_birth(minimum_age=18, maximum_age=80)
        
        # Calculate the cover multiple
        cover_multiple = calculate_cover_multiple(commencement_date, dob)
        
        writer.writerow([
            fake.random_number(digits=9),  # Proposal number
            fake.random_number(digits=9),  # Policy number
            random.choice(['A', 'B', 'C']),  # Premium frequency
            random.choice(['301', '302', '303']),  # Product code
            random.choice(['Product A', 'Product B', 'Product C']),  # Product name
            issuance_date.strftime('%d/%m/%Y'),  # Issuance date
            commencement_date.strftime('%d/%m/%Y'),  # Commencement date
            fake.random_number(digits=6),  # Net premium
            fake.random_number(digits=6),  # Basic sum assured
            random.choice(['M', 'F']),  # Insured sex
            dob.strftime('%d/%m/%Y'),  # Insured DOB
            cover_multiple,  # Cover multiple
            fake.random_number(digits=2),  # Benefit term
            fake.random_number(digits=9),  # Basic cash value
            fake.random_letter() + '-' + str(fake.random_number(digits=2)),  # Group code
            random.choice(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'REINSTATED']),  # Policy status
            fake.random_number(digits=1)  # Status code
        ])

In [9]:
from datetime import datetime
date_int = 26628
def int_to_date(date_int):
    year = date_int // 10000
    month = (date_int // 100) % 100
    day = date_int % 100
    
    return datetime(year, month, day).strftime("%d-%m-%Y")

int_to_date(26628)

ValueError: month must be in 1..12

In [1]:
import pandas as pd

# Read the Excel file into a pandas DataFrame
excel_file = "data.xlsx"  # Replace "your_excel_file.xlsx" with the path to your Excel file
df = pd.read_excel(excel_file)

# Specify the path where you want to save the CSV file
csv_file = "output_file.csv"  # Change "output_file.csv" to the desired CSV file path

# Save the DataFrame to a CSV file
df.to_csv(csv_file, index=False)  # Set index=False to avoid saving row numbers as a column in the CSV file


In [23]:
import numpy as np

# Example function for calculation
def calculate_value(x):
    return x**2  # Square of the input value

# Method 1: Vectorized operation
start = 0
end = 10
num_elements = 10

x_values = np.linspace(start, end, num_elements, dtype=int, endpoint=False)
print(x_values)
my_array = calculate_value(x_values)

print("Method 1 - Vectorized operation:")
print(my_array)

[0 1 2 3 4 5 6 7 8 9]
Method 1 - Vectorized operation:
[ 0  1  4  9 16 25 36 49 64 81]


In [12]:
my_array[6]

36

In [2]:
import time

def squaring():
    start_time = time.time()
    x = []
    for i in range(1, 200001):
        val = i ** 2
        x.append(val)
    print("Total Time:", (time.time() - start_time))
    print(len(x))
    return x

squaring()

Total Time: 0.027985572814941406
200000


[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

In [7]:
import numpy as np

def squaringII():
    start_time = time.time()
    start = 1
    end = 21
    num_elements = 20
    x_values = np.linspace(start, end, num_elements, dtype=int, endpoint=False)
    y = x_values ** 2
    print("Total Time:",(time.time() - start_time))
    return y

squaringII()

Total Time: 0.0


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [16]:
from datetime import datetime, timedelta
def months_into_days(comm_date, start_date):
    date_a = datetime.strptime(comm_date, "%m/%d/%Y")
    date_b = datetime.strptime(start_date, "%m/%d/%Y")
    # date_a = datetime.strptime(comm_date, "%d/%m/%Y")
    # date_b = datetime.strptime(start_date, "%d/%m/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

In [17]:
import time
from datetime import datetime, timedelta

def calculate_policy_month(commencement_date, total_policy_months, start_date):
        start_time = time.time()
        policy_month_col = [months_into_days(commencement_date, start_date)]
        print(policy_month_col[0])
        total_iterations = total_policy_months - policy_month_col[0]
        print(total_iterations)
        for i in range(1, total_iterations):
            try:
                if((policy_month_col[i-1] + 1) < total_policy_months):
                    policy_month_col.append(policy_month_col[i-1] + 1)
                else:
                     policy_month_col.append(0)
            except ValueError:
                    policy_month_col.append(0)
        print("Total Time:",(time.time() - start_time))
        return policy_month_col

In [15]:
for i in range(1, 3):
    print(i)


1
2


In [21]:
calculate_policy_month("6/30/2021", 132, "1/1/2021")

-5
137
Total Time: 0.0012671947479248047


[-5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131]

In [4]:
import numpy as np
import time
import pandas as pd

def calculate_policy_month(commencement_date, total_policy_months, start_date):
    start_time = time.time()
    pol_month_val = months_into_days(commencement_date, start_date)
    print("Pol valu:",pol_month_val)
    total_arr_val = (total_policy_months - pol_month_val) + 1
    print("Total arr val:",total_arr_val)
    policy_month_col = np.zeros(total_arr_val, dtype=int)
#     policy_month_col = np.zeros(total_policy_months, dtype=int)
    policy_month_col[0] = pol_month_val
#     policy_month_col[0] = months_into_days(commencement_date, start_date)
#     total_iterations = total_policy_months - policy_month_col[0]
    
    if total_arr_val > 0:
        incremental_values = np.arange(1, total_arr_val)
        print("Incremental Values:",incremental_values)
        policy_month_col[1:total_arr_val] = np.minimum(
            policy_month_col[0] + incremental_values, total_policy_months)
    print("Total Time:",(time.time() - start_time))
    print(len(policy_month_col))
    table = {
        'Policy Month': policy_month_col
    }
    df = pd.DataFrame(table)
    return df

In [5]:
#calculate_policy_month("4/28/2015", 132, "1/1/2021")
calculate_policy_month("1/24/2012", 60, "1/1/2021")

Pol valu: 110
Total arr val: -49


ValueError: negative dimensions are not allowed

In [20]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [23]:
x= []
x[0:5] = np.minimum(132, 132)
x

TypeError: can only assign an iterable